#!/bin/bash
# This test is generated by AI to test my hand-written script
# Usage: ./test-backup-script.sh

set -uo pipefail

SCRIPT="./backup-script.sh"
[[ -f "$SCRIPT" ]] || { echo "Script not found: $SCRIPT"; exit 1; }

ROOT=$(mktemp -d)
BEFORE="$ROOT/hpc-dir-before"
AFTER="$ROOT/hpc-dir-after"
TARGET="$ROOT/target"
trap 'rm -rf "$ROOT"' EXIT

# pull only diff_checker() out of the script (avoid running main's loop)
eval "$(awk '/^diff_checker\(\) \{/,/^}/' "$SCRIPT")"

# --- build fixture (matches the before/after screenshot) ---
mkdir -p "$BEFORE/example_dir" "$AFTER/example_dir"

: > "$BEFORE/example_dir/empty3.txt"
echo "v1" > "$BEFORE/example_dir/not-empty3.txt"
: > "$BEFORE/empty.txt"
: > "$BEFORE/empty2.txt"                       # deleted in "after"
echo "v1" > "$BEFORE/not-empty.txt"
echo "v1" > "$BEFORE/not-empty2.txt"

: > "$AFTER/example_dir/empty2.txt"            # new file
: > "$AFTER/example_dir/empty3.txt"
echo "v2 - CHANGED" > "$AFTER/example_dir/not-empty3.txt"   # content changed
: > "$AFTER/empty.txt"
echo "v1" > "$AFTER/not-empty.txt"
echo "v2 - CHANGED" > "$AFTER/not-empty2.txt"               # content changed

# --- run ---
mkdir -p "$TARGET"
WATCHED_FOLDER="$AFTER"
diff_checker "$BEFORE" "$AFTER" "$TARGET"

# --- checks ---
pass=0
fail=0

check() {
  local desc="$1" cond="$2"
  if eval "$cond"; then
    echo "PASS: $desc"
    pass=$((pass + 1))
  else
    echo "FAIL: $desc"
    fail=$((fail + 1))
  fi
}

check "new file example_dir/empty2.txt exists"          '[[ -f "$TARGET/example_dir/empty2.txt" ]]'
check "modified not-empty2.txt exists"                  '[[ -f "$TARGET/not-empty2.txt" ]]'
check "modified example_dir/not-empty3.txt exists"      '[[ -f "$TARGET/example_dir/not-empty3.txt" ]]'
check "unchanged empty.txt is NOT copied"               '[[ ! -e "$TARGET/empty.txt" ]]'
check "unchanged not-empty.txt is NOT copied"           '[[ ! -e "$TARGET/not-empty.txt" ]]'
check "unchanged example_dir/empty3.txt is NOT copied"  '[[ ! -e "$TARGET/example_dir/empty3.txt" ]]'
check ".deleted.info lists deleted empty2.txt"          'grep -q "empty2.txt" "$TARGET/.deleted.info" 2>/dev/null'

echo "----"
echo "Result: $pass passed, $fail failed"
[[ "$fail" -eq 0 ]]